name: Build and deploy Python app to Azure Web App - django-sql-test-app

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ODBC build prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc-dev

      - name: Show ODBC headers (optional)
        run: |
          pkg-config --cflags odbc || true
          dpkg -L unixodbc-dev | grep -E 'sql.h|sqlext.h' || true

      # >>> Bump pyodbc to a Python 3.11-friendly version
      - name: Patch requirements to upgrade pyodbc
        run: |
          sed -i 's/^pyodbc==4\.0\.32$/pyodbc==4.0.39/' requirements.txt
          echo "Updated requirements.txt:"
          grep -n '^pyodbc' requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'django-sql-test-app'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C8DB1CF38CEE44FCA9502C27083CDCD3 }}
